[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
    ./install -all
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline'
hook_add = '''
    let g:airline_theme = 'luna'
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#buffer_idx_mode = 1
    let g:airline#extensions#tabline#fnamemod = ':t'
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    set signcolumn=yes
    let g:gitgutter_async = 1
    let g:gitgutter_sign_modified = 'rw'
    highlight GitGutterAdd ctermfg=green
    highlight GitGutterChange ctermfg=yellow
    highlight GitGutterDelete ctermfg=red
    highlight GitGutterChangeDelete ctermfg=yellow
'''

[[plugins]]
repo = 'preservim/nerdtree'
hook_add='''
    let NERDTreeShowHidden=1
    nnoremap <leader>e :NERDTreeFind<CR>:vertical res 30<CR>
    set hidden
    nnoremap <leader>b :bprev<CR>
    nnoremap <leader>n :bnext<CR>
    nnoremap bd :bd<CR>
'''

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
    let g:rainbow_active = 1
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
    nmap <leader> <Plug>(easymotion-prefix)
    let g:EasyMotion_do_mapping = 0
    nmap <leader>w <Plug>(easymotion-jumptoanywhere)
    nmap <leader>jk <Plug>(easymotion-sol-bd-jk)
    nmap <leader>s <Plug>(easymotion-s2)
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
build = '''
    coc#util#install()
'''
hook_add = '''
    inoremap <silent><expr> <C-j> coc#pum#visible() ? coc#pum#next(1) : "\<C-j>"
    inoremap <silent><expr> <C-k> coc#pum#visible() ? coc#pum#prev(1) : "\<C-k>"
    inoremap <silent><expr> <Enter> coc#pum#visible() ? coc#pum#confirm() : "\<Enter>"
    inoremap <silent><expr> <Esc> coc#pum#visible() ? coc#pum#cancel() : "\<Esc>"
'''

[[plugins]]
repo = 'jonathanfilip/vim-lucius' 

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'gosukiwi/vim-atom-dark'

[[plugins]]
repo = 'jdkanani/vim-material-theme'

[[plugins]]
repo = 'w0ng/vim-hybrid'

